stages:
  - test

variables:
  UV_CACHE_DIR: .uv-cache
  UV_CACHE_POLICY: pull

default:
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - $UV_CACHE_DIR
      policy:  $UV_CACHE_POLICY
  before_script:
    - uv sync --frozen

uv-sync:
  stage: .pre
  variables:
    UV_CACHE_POLICY: pull-push
  script: 
    - uv cache prune --ci

uv-lock-check:
  stage: test
  before_script: []
  cache: []
  script:
    - uv lock --check

pytest:
  stage: test
  script:
    - uvx pytest

create-schedule:
  stage: test
  script:
    - uv run make_schedule.py
    - file -f *1.jpg
    - file -f *2.jpg
